---
title: "Statistical Data"
author: "Rizza Pudao"
date: "2023-02-04"
output: html_document
---


```{r}
library(readxl)
rizzapootz <- read_excel("rizzapootz.xlsx")
View(rizzapootz)
```

```{r}
# Store the data in the variable my_data
my_data <- rizzapootz
```

```{r}
# Print the first 5 rows
head(my_data, 5)
```

# Descriptive statistics for a single group

## Measure of central tendency: mean, median, mode



```{r}
# Compute the mean value
mean(my_data$`Shoe Size`)
```

```{r}
# Compute the median value
median(my_data$`Shoe Size`)
```

```{r}
# Compute the mode
# install.packages("modeest")
require(modeest)
mfv(my_data$`Shoe Size`)
```

```{r}
# Compute the minimum value
min(my_data$`Shoe Size`)
```

#Measure of variablity
## Range: minimum & maximum


```{r}
# Compute the maximum value
max(my_data$`Shoe Size`)
```

```{r}
# Range
range(my_data$`Shoe Size`)
```


##Interquartile range

```{r}
quantile(my_data$`Shoe Size`)
```


```{r}
quantile(my_data$`Shoe Size`, seq(0, 1, 0.1))
```


```{r}
IQR(my_data$`Shoe Size`)
```

##Variance and standard deviation

```{r}
# Compute the variance
var(my_data$`Shoe Size`)
# Compute the standard deviation =
# square root of th variance
sd(my_data$`Shoe Size`)
```

##Median absolute deviation

```{r}
# Compute the median
median(my_data$`Shoe Size`)
# Compute the median absolute deviation
mad(my_data$`Shoe Size`)
```

```{r}
summary(my_data$`Shoe Size`)
```

```{r}
summary(my_data, digits = 1)
```


#sapply() function

```{r}
# Compute the mean of each column
sapply(my_data[, -1], mean)
```


```{r}
# Compute quartiles
sapply(my_data[, -1], quantile)
```

```{r}
# Compute descriptive statistics
library(pastecs)
res <- stat.desc(my_data[, -5])
round(res, 2)
```

```{r}
mean(my_data$`Shoe Size`, na.rm = TRUE)
```

#Graphical display of distributions

```{r}
library(ggpubr)
```

```{r}
ggboxplot(my_data, y = "Shoe Size", width = 0.5)
```

```{r}
gghistogram(my_data, x = "Age", bins = 9, 
             add = "mean")
```

```{r}
ggecdf(my_data, x = "Age")
```

```{r}
ggqqplot(my_data, x = "Age")
```






























